version: '3'

services:

  consumer:
    build: ./consumer
    container_name: consumer
    environment:
      KAFKA_BROKER_URL: 'broker:9092'
      SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      TRANSACTIONS_TOPIC: 'create-user-request'
      LEGIT_TOPIC: 'streaming.transactions.legit'
      FRAUD_TOPIC: 'streaming.transactions.fraud'

networks:
  default:
    external:
      name: kafka-network
