version: '3'

services:

  producer:
    build: ./producer
    container_name: producer
    network_mode: "host"
    environment:
      KAFKA_BROKER_URL: 'localhost:9092'
      SCHEMA_REGISTRY_URL: 'http://localhost:8081'
      TRANSACTIONS_TOPIC: 'create-user-request'
      TRANSACTIONS_PER_SECOND: 1000
