version: '3'

services:

  consumer:
    build: ./consumer
    container_name: consumer
    network_mode: "host"
    environment:
      KAFKA_BROKER_URL: 'localhost:9092'
      SCHEMA_REGISTRY_URL: 'http://localhost:8081'
      TRANSACTIONS_TOPIC: 'create-user-request'
      LEGIT_TOPIC: 'streaming.transactions.legit'
      FRAUD_TOPIC: 'streaming.transactions.fraud'
